[package]
name = "argus-infrastructure"
version.workspace = true
edition.workspace = true

[dependencies]
argus-domain.workspace = true
argus-application.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
async-trait.workspace = true
thiserror.workspace = true
portable-pty = "0.8"
tiny_http = "0.12"
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros", "fs", "process"] }
notify-debouncer-mini.workspace = true
trash.workspace = true
ignore = "0.4"
grep-searcher = "0.1"
grep-regex = "0.1"
grep-matcher = "0.1"
syntect = { version = "5", default-features = false, features = ["default-fancy"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.52"
