[package]
name = "argus-application"
version.workspace = true
edition.workspace = true

[dependencies]
argus-domain.workspace = true
serde.workspace = true
uuid.workspace = true
thiserror.workspace = true
async-trait.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
